site_name: CSCI 232 - Data Structures and Algorithms
site_url: https://isaacovercast.github.io/CSCI232
repo_url: https://isaacovercast.github.io/CSCI232
edit_uri: edit/master/docs/

theme:
  name: material
  highlightjs: true
  palette:
    - scheme: default
      primary: blue
      ascent: indigo
      toggle: 
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      ascent: indigo
      toggle: 
        icon: material/lightbulb
        name: Switch to lightmode
  favicon: /images/favicon.ico
  icon:
    logo: material/hexagon-multiple-outline
  features:
    - navigation.instant     # revisit this if reloading is not great...
    - navigation.tracking
    - search.highlight    # - navigation.indexes
    - search.suggest
    - content.code.annotate # 
    - content.code.copy
    # - toc.follow    
    # - navigation.expand    
    # - navigation.sections
    # - navigation.tabs      

extra_javascript:

extra_css:
  - stylesheets/pages.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/monokai.min.css  
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/monokai-sublime.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16-unikitty-light.min.css  

extra_javascript:
  # - javascripts/extra.js
  # - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js  
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - md_in_html
  - pymdownx.details  
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      
  # - pymdownx.highlight:
  #     use_pygments: true
  #     pygments_lang_class: true

nav: 
  - Syllabus: index.md
  - Sessions: 
    - Session 1 - (3/24): sessions/session-1
  - Tutorials:
    - Session 1 - (3/24):
        - 1.0 -- Interactive hash tables: tutorials/1.0-interactive-hash-tables
        - 1.1 -- Hash table experiments: tutorials/1.1-hash-table-experiments
  - Resources:
    - Textbook - Data Structures and Algorithms in Python (Goodrich, Tamassia, & Goldwasser): https://www.wiley.com/en-us/Data+Structures+and+Algorithms+in+Python%2C+1st+Edition-p-9781118290279
    - Additional Reading - Grokking Algorithms (Bhargava): https://livebook.manning.com/book/grokking-algorithms-second-edition
    - Supplementary Materials:
      - TAOCP (Knuth): https://www-cs-faculty.stanford.edu/~knuth/taocp.html
      - Algorithms (Sedgwick & Wayne): https://algs4.cs.princeton.edu/home/
      - Algorithms (S&W) Online content: https://www.coursera.org/learn/algorithms-part1
  - External Links: 
    - CSCI 232 Discord Server: https://discord.gg/c3PSEk3HU9
    - Launch CSCI 232 Binder: https://mybinder.org/v2/gh/isaacovercast/CSCI232/HEAD
  - Course Dev Notes: pages/devnotes
  